### ISSUE TITLE
Token allowance component

### ISSUE THREAD

**Issue by dovalid** [AgoraSpaceDAO/agora-frontend#52]
Right now the conditional UI rendering for the token allowance machine is duplicated in StakingModal and UnstakingModal. We should extract it to a component

**Comment by cs-balazs** [comment]
The first commit on this issue's branch is just a basic separation of the duplicated code, but I had an idea that I wanted to try out.
The concept behind this implementation is not having to deal with the allowance state inside StakingModal and UnstakingModal (and in future components where we need allowance), just create the modal using the Allowance components instead of the chakra ones.
The parent AllowanceModal component (instead of the chakra Modal) provides the allowance state to the Body and the Footer, where we use it as we did before.

Some things that I had to change for this:
- There are now separate error components for the allowance and the other action. This is because we can't access the allowance state from the StakeingModal and UnstakingModal components (which was the idea behind the whole thing), so there is a separate Error component for the allowance inside AllowanceModalBody.
- The notification hiding happens with a useEffect now, which can lead to some unnecessary checks, but I don't think it's really that significant, since this only runs twice in an error-free flow.

I like how we don't have to use the allowance state in the Modals, but this would need some refactor if we end up needing this information in the future, or other components (right now I don't see a reason why we would need that)
